[package]
name = "plugin_hello"
version = "0.1.0"
authors = ["qin <qinsong007@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
futures = "0.3"
deno_core = "0.42"

